sudo: required
addons:
  ssh_known_hosts: beech.bjrm.de
services:
- docker
script:
- make setup generate
before_install:
- openssl aes-256-cbc -K $encrypted_fceee56ae713_key -iv $encrypted_fceee56ae713_iv
  -in deploy_key.enc -out /tmp/deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_key
- ssh-add /tmp/deploy_key
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after -e "ssh -p 222" $TRAVIS_BUILD_DIR/public/ deploy_kalembe@beech.bjrm.de:/opt/web_static/kalembe.de/
  on:
    branch: master
